jobs:

- job: Windows
  pool:
    vmImage: vs2017-win2016
  strategy:
    maxParallel: 2
    matrix:
      debug:
        _configuration: Debug
      release:
        _configuration: Release
  steps:
  - task: DotNetCoreCLI@2
    displayName: Restore
    inputs:
      command: restore
  - task: DotNetCoreCLI@2
    displayName: Build
    inputs:
      command: build
      arguments: -c $(_configuration)
  - task: DotNetCoreCLI@2
    displayName: Test
    inputs:
      command: test
      arguments: -c $(_configuration) --no-restore --no-build
  - task: DotNetCoreCLI@2
    displayName: Pack
    inputs:
      command: pack
      configuration: $(_configuration)
      nobuild: true
  - task: PublishBuildArtifacts@1
    displayName: Publish Package
    condition: and(succeeded(), eq(variables['_configuration'], 'Release'))
    inputs:
      pathtoPublish: $(Build.ArtifactStagingDirectory)
      artifactName: packages

- job: Linux
  pool:
    vmImage:  ubuntu-16.04
  strategy:
    maxParallel: 2
    matrix:
      debug:
        _configuration: Debug
      release:
        _configuration: Release
  steps:
  - task: DotNetCoreCLI@2
    displayName: Restore
    inputs:
      command: restore
  - task: DotNetCoreCLI@2
    displayName: Build
    inputs:
      command: build
      arguments: -c $(_configuration)
  - task: DotNetCoreCLI@2
    displayName: Test
    inputs:
      command: test
      arguments: -c $(_configuration) --no-restore --no-build
  - task: DotNetCoreCLI@2
    displayName: Pack
    inputs:
      command: pack
      arguments: -c $(_configuration) --no-restore --no-build
